#!/usr/bin/env bash
ANTLR_FILES="$PWD/src/parser"
antlr -visitor -no-listener -Dlanguage=TypeScript -o $ANTLR_FILES $PWD/src/fass.g4

rm $ANTLR_FILES/*.interp
rm $ANTLR_FILES/*.tokens

echo "Compiled Fass"
